name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
          run: |
            go get .
      - name: Build
          env: 
          run: env GOOS=js GOARCH=wasm go build -o ./gh/mygame.wasm ./main.go 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh

permissions:
  contents: write